export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const CHANGES_COMMENTS_VIEW = 'CHANGES_COMMENTS_VIEW';
export const LAST_COMMENTS = 'LAST_COMMENTS';
export const ALL_COMMENTS = 'ALL_COMMENTS';
